image: coin/archlinux

env:
 global:
   - INSTALL_DIR=~/GrayBat

script:
  - echo "# SCRIPT"
  - pwd
  - ls -lah
  - pacman -S gcc clang boost openmpi
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - echo "Clang++ build test"
  - cmake -DCMAKE_CXX_COMPILER=`which clang++` ..
  - make GoL
  - mpiexec --allow-run-as-root ./GoL 90 10
  - rm * -rf
  - echo "G++ build test"
  - cmake -DCMAKE_CXX_COMPILER=`which g++` ..
  - make GoL
  - mpiexec --allow-run-as-root ./GoL 90 10

before_script:
  - echo "# BEFORE SCRIPT"
  - pwd
  - ls -lah

after_script:
  - echo "# AFTER SCRIPT"
  - pwd
  - ls -lah
