image: archlinux/base

env:
 global:
   - INSTALL_DIR=~/GrayBat

script:
  - echo "# SCRIPT"
  - pwd
  - ls -lah
  - git submodule init
  - git submodule update
  - mkdir build
  - cd build
  - cmake ..
  - make GoL
  - mpirun ./GoL 90 1

before_script:
  - echo "# BEFORE SCRIPT"
  - pwd
  - ls -lah

after_script:
  - echo "# AFTER SCRIPT"
  - pwd
  - ls -lah