image: coin/archlinux

env:
 global:
   - INSTALL_DIR=~/GrayBat

script:
  - echo "# SCRIPT"
  - pwd
  - ls -lah
  - mkdir build
  - cd build
  - echo "######################"
  - echo "# Clang++ build test #"
  - echo "######################"  
  - export CXX=clang++
  - cmake ..
  - make zmq_signaling
  - make example
  - ./zmq_signaling&
  - make test
  - mpiexec --allow-run-as-root ./gol 90 10
  - killall zmq_signaling
  - rm * -rf
  - echo "##################"
  - echo "# G++ build test #"
  - echo "##################"  
  - export CXX=g++
  - cmake ..
  - make zmq_signaling
  - make check
  - make example
  - ./zmq_signaling&
  - make test
  - mpiexec --allow-run-as-root ./gol 90 10
  - killall zmq_signaling
  - rm * -rf

before_script:
  - echo "# BEFORE SCRIPT"
  - pwd
  - ls -lah

after_script:
  - echo "# AFTER SCRIPT"
  - pwd
  - ls -lah
