image: coin/archlinux

env:
 global:
   - INSTALL_DIR=~/GrayBat

script:
  - echo "# SCRIPT"
  - pwd
  - ls -lah
  - mkdir build
  - cd build
  - echo "Clang++ build test"
  - export CXX=clang++
  - cmake ..
  - make zmq_signaling
  - ./zmq_signaling&
  - make check
  - mpiexec --allow-run-as-root -n 2 ./check
  - killall zmq_signaling
  - make example
  - mpiexec --allow-run-as-root ./gol 90 10
  - rm * -rf
  - echo "G++ build test"
  - export CXX=g++
  - cmake ..
  - make zmq_signaling
  - ./zmq_signaling&
  - make check
  - mpiexec --allow-run-as-root -n 2 ./check
  - killall zmq_signaling
  - make examaple
  - mpiexec --allow-run-as-root ./gol 90 10

before_script:
  - echo "# BEFORE SCRIPT"
  - pwd
  - ls -lah

after_script:
  - echo "# AFTER SCRIPT"
  - pwd
  - ls -lah
