
language: cpp
sudo: false

cache:
  apt: true
  directories:
    - $HOME/.cache/spack

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - tree
        - gcc-6
        - g++-6 # also possible: g++5.2 or g++-6
        - gfortran-6

env:
  global:
    - GRAYBAT_ROOT: $TRAVIS_BUILD_DIR
    - SPACK_DIR: $HOME/.cache/spack
    - SPACK_HZDR_DIR: $HOME/spack-repo
  matrix:
    - COMPILER=gcc  STRATEGY=""

before_install:
  - export CMAKE_FLAGS="-DCMAKE_CXX_FLAGS=\"-Werror\""
  - if [ "$COMPILER" == "gcc" ]; then
        echo "Using g++-6";
        export CXX=g++-6;
        export CC=gcc-6;
    elif [ "$COMPILER" == "clang" ]; then
        echo "Using clang++-3.5 & sequential threads ...";
        export CXX=clang++-3.5;
        export CC=clang-3.5;
    fi
  - echo "$CMAKE_FLAGS"
  - echo "$CXX $CC"
  - $CXX --version
  - $CC --version

install:
  - echo "Install stage"
  - tree -L 3 $SPACK_DIR
  - rm -fr $SPACK_DIR
  #############################################################################
  # SPACK                                                                     #
  #############################################################################
  - if [ ! -d "$SPACK_DIR" ] ; then
      git clone https://github.com/LLNL/spack.git $SPACK_DIR;
    fi
  - if [ ! -d "$SPACK_HZDR_DIR" ] ; then
      git clone https://github.com/ComputationalRadiationPhysics/spack-repo.git $SPACK_HZDR_DIR;
    fi
  - $SPACK_DIR/bin/spack repo add $SPACK_HZDR_DIR || true
  - travis_wait 50 $SPACK_DIR/bin/spack install graybat@develop +mpi +zeromq
  - tree -L 3 $SPACK_DIR
  - tree -L 3 $SPACK_HZDR_DIR

script:
  - echo "Script state"
