
language: cpp
sudo: false

cache:
  apt: true
  directories:
    - $HOME/.cache/cmake
    - $HOME/.cache/boost
    - $HOME/.cache/zmq
    - $HOME/.cache/grpc
    - $HOME/.cache/protobuf

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - tree
        - gcc-6
        - g++-6 # also possible: g++5.2 or g++-6
        - gfortran-6

env:
  global:
    - GRAYBAT_ROOT: $TRAVIS_BUILD_DIR
  matrix:
    - COMPILER=gcc  STRATEGY=""

before_install:
  - export CMAKE_FLAGS="-DCMAKE_CXX_FLAGS=\"-Werror\""
  - if [ "$COMPILER" == "gcc" ]; then
        echo "Using g++-6";
        export CXX=g++-6;
        export CC=gcc-6;
    elif [ "$COMPILER" == "clang" ]; then
        echo "Using clang++-3.5 & sequential threads ...";
        export CXX=clang++-3.5;
        export CC=clang-3.5;
    fi
  - echo "$CMAKE_FLAGS"
  - echo "$CXX $CC"
  - $CXX --version
  - $CC --version

install:
  - echo "Install stage"
  #############################################################################
  # SPACK                                                                     #
  #############################################################################
  - git clone https://github.com/LLNL/spack.git
  - git clone https://github.com/ComputationalRadiationPhysics/spack-repo.git
  - ./spack/bin/spack repo add ./spack-repo
  - ./spack/bin/spack install graybat@develop +mpi +zeromq


script:
  - echo "Script state"
