#! /bin/fish

set -x GRAYBAT_ZMQ_MASTER_URI          tcp://127.0.0.1:5000
set -x GRAYBAT_ZMQ_LOCAL_BASE_URI      tcp://127.0.0.1
set -x GRAYBAT_ZMQ_LOCAL_BASE_PORT     5001
set -x GRAYBAT_ZMQ_GLOBAL_CONTEXT_SIZE 2

